// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vpfrtytxeimezwxhhtuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZnJ0eXR4ZWltZXp3eGhodHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzkxMzcsImV4cCI6MjA3NDMxNTEzN30.l964YeRl-cJPEHTqR3zDsO6rCd0uyIiFlOU4QU7GKZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.sessionStorage : undefined, // Changed to sessionStorage
    persistSession: true, // Explicitly ensure session persistence within the tab
    autoRefreshToken: true, // Ensure tokens are refreshed automatically
    detectSessionInUrl: true, // Important for handling redirects after auth events
  },
});